[package]
name = "reapi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
redis-module = "2.0.7"
tokio = { version = "1.43.0", features = ["full"] }
axum = "0.8.1"
serde_json = "1.0.138"
serde = "1.0.217"
anyhow = "1.0.95"
